### ISSUE TITLE
Strapi Not Found

### ISSUE THREAD

**Issue by cheezebot098** [kevinfaveri/solana-candy-factory#11]
Hi!

When I got to run "yarn nft-manager" I get the following error:

"Error loading the local develop command. Strapi might not be installed in your "node_modules". You may need to run "npm install"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."

I have Strapi installed. Not sure what I'm doing wrong. Thanks for any help!

**Comment by kevinfaveri** [comment]
Hey! Please try deleting your node_modules inside the ./nft-manager folder and on the root of the project too... And then run `yarn install` at the root of the project. If it still not works, kindly provide me a code sandbox or a Github fork so I can reproduce the error here.

**Comment by cheezebot098** [comment]
`yarn install` isn't creating node_modules inside the ./nft-manager folder. It's only creating it in the root of the project.

Also I'm getting these errors when running `yarn install`

`error /Users/michaelpersson/Desktop/solana-candy-factory-main/node_modules/postinstall-postinstall: Command failed.
Exit code: 1
Command: node ./run.js
Arguments: 
Directory: /Users/michaelpersson/Desktop/solana-candy-factory-main/node_modules/postinstall-postinstall
Output:
error strapi@3.6.8: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.8.0"
error Found incompatible module.
error Command failed with exit code 1.
node:child_process:903
    throw err;
    ^

Error: Command failed: yarn run postinstall
error strapi@3.6.8: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.8.0"
error Found incompatible module.
error Command failed with exit code 1.

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.<anonymous> (/Users/michaelpersson/Desktop/solana-candy-factory-main/node_modules/postinstall-postinstall/run.js:15:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(406) [Uint8Array] [
      121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
       50,  50,  46,  49,  49,  10,  36,  32, 112,  97, 116,  99,
      104,  45, 112,  97,  99, 107,  97, 103, 101,  32,  38,  38,
       32,  99, 100,  32,  46,  47, 110, 102, 116,  45, 109,  97,
      110,  97, 103, 101, 114,  32,  38,  38,  32, 121,  97, 114,
      110,  10, 112,  97, 116,  99, 104,  45, 112,  97,  99, 107,
       97, 103, 101,  32,  54,  46,  52,  46,  55,  10,  65, 112,
      112, 108, 121, 105, 110, 103,  32, 112,  97, 116,  99, 104,
      101, 115,  46,  46,
      ... 306 more items
    ],
    Buffer(196) [Uint8Array] [
      101, 114, 114, 111, 114,  32, 115, 116, 114,  97, 112, 105,
       64,  51,  46,  54,  46,  56,  58,  32,  84, 104, 101,  32,
      101, 110, 103, 105, 110, 101,  32,  34, 110, 111, 100, 101,
       34,  32, 105, 115,  32, 105, 110,  99, 111, 109, 112,  97,
      116, 105,  98, 108, 101,  32, 119, 105, 116, 104,  32, 116,
      104, 105, 115,  32, 109, 111, 100, 117, 108, 101,  46,  32,
       69, 120, 112, 101,  99, 116, 101, 100,  32, 118, 101, 114,
      115, 105, 111, 110,  32,  34,  62,  61,  49,  48,  46,  49,
       54,  46,  48,  32,
      ... 96 more items
    ]
  ],
  pid: 95611,
  stdout: Buffer(406) [Uint8Array] [
    121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
     50,  50,  46,  49,  49,  10,  36,  32, 112,  97, 116,  99,
    104,  45, 112,  97,  99, 107,  97, 103, 101,  32,  38,  38,
     32,  99, 100,  32,  46,  47, 110, 102, 116,  45, 109,  97,
    110,  97, 103, 101, 114,  32,  38,  38,  32, 121,  97, 114,
    110,  10, 112,  97, 116,  99, 104,  45, 112,  97,  99, 107,
     97, 103, 101,  32,  54,  46,  52,  46,  55,  10,  65, 112,
    112, 108, 121, 105, 110, 103,  32, 112,  97, 116,  99, 104,
    101, 115,  46,  46,
    ... 306 more items
  ],
  stderr: Buffer(196) [Uint8Array] [
    101, 114, 114, 111, 114,  32, 115, 116, 114,  97, 112, 105,
     64,  51,  46,  54,  46,  56,  58,  32,  84, 104, 101,  32,
    101, 110, 103, 105, 110, 101,  32,  34, 110, 111, 100, 101,
     34,  32, 105, 115,  32, 105, 110,  99, 111, 109, 112,  97,
    116, 105,  98, 108, 101,  32, 119, 105, 116, 104,  32, 116,
    104, 105, 115,  32, 109, 111, 100, 117, 108, 101,  46,  32,
     69, 120, 112, 101,  99, 116, 101, 100,  32, 118, 101, 114,
    115, 105, 111, 110,  32,  34,  62,  61,  49,  48,  46,  49,
     54,  46,  48,  32,
    ... 96 more items`

Not sure if any of that is causing it. I will get a fork of mine for you to try and reproduce the error.

**Comment by cheezebot098** [comment]
Here is my fork of this project. Nothing was changed code wise. I was just trying to follow the tutorial.

https://github.com/cheezebot098/solana-candy-factory.git

**Comment by cheezebot098** [comment]
Im closing this. All I had to do was downgrade npm to 14.17.0

Not sure if there is a better version to be on, but its working now!

**Comment by kevinfaveri** [comment]
Thank you! I will add something on the readme.md

**Comment by cheezebot098** [comment]
Well Im back with another issue..

When trying to run both these commands `yarn update-creator-all-rows` and `yarn generate-nfts-sources` I get these errors:

"(node:99635) UnhandledPromiseRejectionWarning: Error: Forbidden
    at Strapi.request (/Users/michaelpersson/Desktop/solana-candy-factory-main/nft-manager/node_modules/strapi-sdk-javascript/build/main/lib/sdk.js:59:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async updateCreatorAllRows (/Users/michaelpersson/Desktop/solana-candy-factory-main/nft-manager/scripts/update-creator-all-rows.js:37:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:99635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:99635) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

**or broken down differently:**

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/Users/michaelpersson/Desktop/solana-candy-factory-main/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

This is beyond my coding knowledge unfortunately

**Comment by kevinfaveri** [comment]
hey! The forbidden error is probably because you did not setup the admin user as specified in the readme: 

```
! NOTE: Be sure to create a user, after you log in with the admin account, that has the role "authenticated", username "admin" and pass "Admin123", as well as add all collections and upload related permissions to the "authenticated" role; otherwise, the yarn update-creator-all-rows and yarn generate-nft-sources commands will not work.

```

No problem, it is a long readme and technical. Also, hopefully this easier to follow guide will be helpful to you (it uses this repo!): https://www.quicknode.com/guides/web3-sdks/how-to-mint-an-nft-on-solana-using-candy-machine

**Comment by cheezebot098** [comment]
I did set up the admin role. Exactly following that specific guide.

<img width="1426" alt="Screen Shot 2021-09-25 at 1 40 34 PM" src="https://user-images.githubusercontent.com/3092900/134781017-f8b0b8fe-0140-4fb1-81a1-2a8f7ba0fd21.png">

**Comment by kevinfaveri** [comment]
Okay, can you validate if on the permission management tool of the nft-manager the "authenticated" role has all permissions?

**Comment by mattchiang777** [comment]
@cheezebot098 This is the area on the management tool where @kevinfaveri mentioned:

![image](https://user-images.githubusercontent.com/5668464/134783063-7e7eaa82-b668-4f1a-b8a2-8f768dbc759b.png)
