### ISSUE TITLE
nf-ts is forbidden

### ISSUE THREAD

**Issue by henry8th** [kevinfaveri/solana-candy-factory#12]
Hi! Thanks for the cool lib

Running into a problem where nf-ts is returning forbidden?
I triple checked to make sure I set the User to have role authenticated username: admin and password: Admin123

Any help would be greatly appreciated.. i'm sure i am just missing something from the docs thanks

**Comment by kevinfaveri** [comment]
The "authenticated" role must have all permissions. You can do that using the nft-manager settings.

**Comment by kevinfaveri** [comment]
This one:
https://github.com/kevinfaveri/solana-candy-factory/issues/11#issuecomment-927167362

**Comment by henry8th** [comment]
Thank you <3
