### ISSUE TITLE
Cannot read property 'trim' of undefined when running yarn setup-dev

### ISSUE THREAD

**Issue by ZEAL-MATCH-LTD** [kevinfaveri/solana-candy-factory#13]
Hello, 

Loving your project.

When running `yarn setup-dev` i get the error `Cannot read property 'trim' of undefined`

It's coming from around line 26 `/devtools/dev/setup-envs-dev.js` and looks like `/logs/dev/candy-machine-start-date.txt` is not being populated by the `update_candy_machine` command.

everything else seems to be working smoothly!

**Comment by kevinfaveri** [comment]
hey bro! You need to update your metaplex cli. If it does not work, ping me here and I will work on it.

**Comment by ZEAL-MATCH-LTD** [comment]
@kevinfaveri Thanks for your swift response. 

```bash
$ metaplex -V
0.0.1
```

Is that not the latest? It looks to be the latest on [npm](https://www.npmjs.com/package/@metaplex/js)

**Comment by kevinfaveri** [comment]
It is always 0.0.1 because they are not updating it... You need to build from source. On the readme.md there is instructions for that.

**Comment by ZEAL-MATCH-LTD** [comment]
If you mean this commant `$ git clone git@github.com:metaplex-foundation/metaplex.git \
  ~/metaplex-foundation/metaplex` then i have already installed and pulled on master for this repo.

**Comment by kevinfaveri** [comment]
Thanks, bro @ZEAL-MATCH-LTD! It seems like Metaplex changed their CLI. I've updated the repo to reflect it and they are working now. Please pull the changes and ping me back

**Comment by ZEAL-MATCH-LTD** [comment]
Pulled and getting a different error again. 

```bash
/Users/zealmatch/.config/yarn/global/node_modules/ts-node/src/index.ts:692
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(2,21): error TS2307: Cannot find module 'fs' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(3,23): error TS2307: Cannot find module 'path' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(4,10): error TS2305: Module '"commander"' has no exported member 'program'.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(5,25): error TS2307: Cannot find module '@project-serum/anchor' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(6,16): error TS2307: Cannot find module 'bn.js' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(7,19): error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(10,41): error TS2307: Cannot find module '@solana/spl-token' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(11,27): error TS2307: Cannot find module '@solana/web3.js' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(30,17): error TS2307: Cannot find module 'loglevel' or its corresponding type declarations.
../../../metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts(627,15): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
```

I've ran a fresh yarn install and also deleted `node_modules` in `root` and `nft-manager`

**Comment by ZEAL-MATCH-LTD** [comment]
Thinking i need to do a fresh build on metaplex foundation. I have to hit the hay but will have a crack at this tomorrow and let you know. 

Unless you see something different.

**Comment by kevinfaveri** [comment]
Yes. You need to reinstall the metaplex repo (clone it) and then run run `npm install` in the `metaplex-foundation/metaplex/js/packages/cli/src/`

**Comment by kevinfaveri** [comment]
Did it work @ZEAL-MATCH-LTD? If so, please close the issue.

**Comment by ZEAL-MATCH-LTD** [comment]
@kevinfaveri Yes! thank you appreciate your help. Feel free to close.

**Comment by imentus-rahul** [comment]
Type mint price [default 1 sol]: 1
Type start date of the minting [default 16 Sep 2021 00:00:00]: 28 Sep 2021 00:00:00
[INFO] Cleaning older cache folder for metaplex
[INFO] Uploading all resources
[INFO] Creating candy machine
[INFO] Setting minting start date (goLiveDate)
./devtools/dev/setup-metaplex-dev.sh: 4: ts-node: not found
./devtools/dev/setup-metaplex-dev.sh: 6: ts-node: not found
./devtools/dev/setup-metaplex-dev.sh: 8: ts-node: not found
$ node ./devtools/dev/setup-envs-dev.js
/home/imentus/Documents/projects/solana-nft/code/github/solana-candy-factory/devtools/dev/setup-envs-dev.js:20
        .trim()
        ^

TypeError: Cannot read property 'trim' of undefined
    at /home/imentus/Documents/projects/solana-nft/code/github/solana-candy-factory/devtools/dev/setup-envs-dev.js:20:9
    at Array.forEach (<anonymous>)
    at /home/imentus/Documents/projects/solana-nft/code/github/solana-candy-factory/devtools/dev/setup-envs-dev.js:13:9
    at FSReqCallback.oncomplete (fs.js:180:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.




Same issue on my side.

**Comment by kevinfaveri** [comment]
You need to reinstall the metaplex repo (clone it) and then run run npm install in the metaplex-foundation/metaplex/js/packages/cli/src/

After you do that, you need to run `yarn setup-dev` and go along with the prompt.

**Comment by ss5nathan** [comment]
Newest version of metaplex binary is broken see https://github.com/metaplex-foundation/metaplex/issues/581#issuecomment-932818807 they recommend using ts-node and running directly. Still have been unable to get this to work on newest version unfortunately.
