### ISSUE TITLE
Question: How to upload many (5-10k) Images?

### ISSUE THREAD

**Issue by ZEAL-MATCH-LTD** [kevinfaveri/solana-candy-factory#14]
Hey! 

I've followed [this blog](https://www.quicknode.com/guides/web3-sdks/how-to-mint-an-nft-on-solana-using-candy-machine) which is very handy however, i can't see how i would be able to upload a collection of images at scale. 

The only way i see it working is if i create my own script that loops over a folder of [png/json] assets and populates the `nfts-sources` folder. 

Is this the recommended way? I can't see any documentation regarding uploading assets at scale, especially multiple assets with differing attributes.

**Comment by kevinfaveri** [comment]
When you run yarn deploy-mainnet it will automatically read the nfts-sources folder and upload them all. But yeah, you still need to use Strapi and then the `yarn generate-nfts-sources` command to make it work. But you can obviously create a script and populate the nfts-sources (but they should follow Metaplex Metadata Standard)

**Comment by imentus-rahul** [comment]
> Hey!
> 
> I've followed [this blog](https://www.quicknode.com/guides/web3-sdks/how-to-mint-an-nft-on-solana-using-candy-machine) which is very handy however, i can't see how i would be able to upload a collection of images at scale.
> 
> The only way i see it working is if i create my own script that loops over a folder of [png/json] assets and populates the `nfts-sources` folder.
> 
> Is this the recommended way? I can't see any documentation regarding uploading assets at scale, especially multiple assets with differing attributes.

Hey, can you help me with the script for uploading NFTs at large scale (10k)? and display them all together on a web app. Could you please update your git repository?
