### ISSUE TITLE
Error when running yarn update-creator-all-rows

### ISSUE THREAD

**Issue by smwein** [kevinfaveri/solana-candy-factory#16]
I get this error when running the update-creator command.

$ node ./scripts/update-creator-all-rows
(node:3303) UnhandledPromiseRejectionWarning: Error: [object Object]
    at Strapi.request (/root/solana-candy-factory/nft-manager/node_modules/strapi-sdk-javascript/build/main/lib/sdk.js:59:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Strapi.login (/root/solana-candy-factory/nft-manager/node_modules/strapi-sdk-javascript/build/main/lib/sdk.js:93:32)
    at async updateCreatorAllRows (/root/solana-candy-factory/nft-manager/scripts/update-creator-all-rows.js:32:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3303) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.47s.

Not sure why.

**Comment by imentus-rahul** [comment]
(node:35256) UnhandledPromiseRejectionWarning: ReferenceError: nfts is not defined
    at updateCreatorAllRows (/home/imentus/Documents/projects/solana-nft/code/github/solana-candy-factory/nft-manager/scripts/update-creator-all-rows.js:51:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 13.61s.
![Screenshot from 2021-09-27 13-17-54](https://user-images.githubusercontent.com/86224847/134866381-0f3ab629-d2a6-4077-a0a3-3cf605c54f46.png)


I'm unable to interact with strapi? what could be the possible reason, admin-Admin123 set, all permission checkboxes ticked!

**Comment by kevinfaveri** [comment]
@imentus-rahul bro you changed the code. It states that the nfts var is not defined.
I suppose you should have a `const nfts = await strapi.getEntries('nf-ts')`

**Comment by EdenShin** [comment]
> @imentus-rahul bro you changed the code. It states that the nfts var is not defined.
> I suppose you should have a `const nfts = await strapi.getEntries('nf-ts')`
> 
> @smwein not sure too bro... Can you share your code for this script?

Hi, I met a similar issue. Error showes below:

$ yarn update-creator-all-rows
yarn run v1.22.11
$ cd ./nft-manager && yarn update-creator-all-rows
$ node ./scripts/update-creator-all-rows
(node:15608) UnhandledPromiseRejectionWarning: Error: [object Object]
    at Strapi.request (/home/yon/NFT/Metaplex/Tutorial/solana-candy-factory-main/nft-manager/node_modules/strapi-sdk-javascript/build/main/lib/sdk.js:59:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.32s.

Thanks a lot.

**Comment by imentus-rahul** [comment]
> @imentus-rahul bro you changed the code. It states that the nfts var is not defined.
> I suppose you should have a `const nfts = await strapi.getEntries('nf-ts')`
> 
> @smwein not sure too bro... Can you share your code for this script?
![Screenshot from 2021-09-28 11-24-16](https://user-images.githubusercontent.com/86224847/135031285-c55d87b6-70ab-47c2-a8ce-6ba04de2b003.png)

**Comment by Yonatan19981** [comment]
I also have a problem. 
![image](https://user-images.githubusercontent.com/60484385/135044109-aac815fa-8358-4de4-be6f-eb2d2d019388.png)

**Comment by wjl8** [comment]
When the program runs to this line, an error is reported. The error is unhandledpromiserejectionwarning: error: forbidden

**Comment by Yonatan19981** [comment]
Do you have any idea how to solve it?

**Comment by wjl8** [comment]
`const nfts = await `strapi.getEntries('nf-ts')
When`` the program runs to this line, an error is reported. The error is unhandledpromiserejectionwarning: error: forbidden

**Comment by Yonatan19981** [comment]
Yes do you have any idea how to fix it?

**Comment by wjl8** [comment]
> 是的，你知道如何解决它吗？

Set permissions，In settings

**Comment by mindell** [comment]
> > 是的，你知道如何解决它吗？
> 
> Set permissions，In settings

it does not work. it also has the authenticated role, confirmed: on user: admin password: Admin123

the error on me is 
```
(node:3685) UnhandledPromiseRejectionWarning: Error: Forbidden
    at Strapi.request
```
on nft-manager
```
[2021-09-28T10:51:31.360Z] debug POST /auth/local (5087 ms) 200
[2021-09-28T10:51:31.410Z] debug GET /nf-ts (28 ms) 403

```

**Comment by EdenShin** [comment]
> > Yes do you have any idea how to fix it?
> 
> Set permissions，In settings

More in detail, refer to this [stackoverflow thread](https://stackoverflow.com/questions/53956118/strapi-api-calling-error-statuscode403-errorforbidden-messageforbi). Open http://localhost:1337/admin/settings/users-permissions/roles/
Select all permissions for the Authenticated Role, then issue solved.

![Screenshot from 2021-09-28 21-54-35](https://user-images.githubusercontent.com/42002965/135101750-3de4aa21-14e0-44e0-ab61-1df578242d04.png)

**Comment by atomicstorm-hca** [comment]
Just want to point out the above issue with Yonatan is not related to the OP issue and still persists.

Yonatan's issue should be separated from this issue.

**Comment by kevinfaveri** [comment]
@atomicstorm-hca I think it is the same one since the error is forbidden. Anyway, I was not able to reproduce these errors by following closely the README.MD. I will update the README.MD to be more detailed like @EdenShin explained. If any of you were to open another issue, please describe again what is happening and provide either a code sandbox or a fork where I can get the code to reproduce.
