### ISSUE TITLE
How can I display my artworks in the index.tsx

### ISSUE THREAD

**Issue by advanztek** [kevinfaveri/solana-candy-factory#17]
Hi \how can I retrieve my artworks and display them in my index.tsx, which of the object holds the data or which component should I import?

Basically what am trying to achieve is pull the data and display it on the website so people can mint, and so it also show the status of each artwork whether it has been minted or not, So if there's a way that I can fetch the data I will like to know.

Really looking forward to your response ASAP if possible bro, your help will really be appreciated.
Thank you in advance

**Comment by kevinfaveri** [comment]
You can just move the raw images to the /public folder os nextjs. Also, for presenting NFT's the user is owner off, you have the option of using the `useWalletNfts` hook. Another option might be tweaking this hook also.

**Comment by advanztek** [comment]
> You can just move the raw images to the /public folder os nextjs. Also, for presenting NFT's the user is owner off, you have the option of using the `useWalletNfts` hook. Another option might be tweaking this hook also.

Thank you once again for responding. I really appreciate, I know disturb you alot. LoL.

**Comment by advanztek** [comment]
> useWalletNfts

I checked the "src/hooks" but there was no useWalletNfts. Please how can I find it.

Thank you.

**Comment by advanztek** [comment]
Hi @kevinfaveri, I updated my repository and console log "useWalletNfts" after importing it but didn't find any data regarding the NFTs that I uploaded which is very important. What am trying to archieve is loop through each of the data and display it for minting, so that users will be able to know the particular token that they're minting. 

Please your response is really appreciated. Thank you.

**Comment by kevinfaveri** [comment]
Hey @advanztek. `useWalletNfts` only work for NFTs in the wallet of the user in the case you want to showcase. This repo currently does not support listing them all by requesting the Metaplex program so you probably need to DYOR on this one
But you can go for a simpler solution: just move your resources to the public folder of the NextJS and request them there, or create a NextJS API endpoint that serves this content.
