### ISSUE TITLE
how to customize index.tsx?

### ISSUE THREAD

**Issue by Cyncra** [kevinfaveri/solana-candy-factory#2]
i luv u kevin!
i don't have react app knowledge.
how to show up remain NFT count in webpage?
how to modify Mint Button style..?

**Comment by kevinfaveri** [comment]
Thank you man! lmao

1 - I will update the repo to feature the counter soon

2 - You can easily customize by using tailwind.css (dyor a bit the website but it is really easy to use, just grab the css classes and input into the className of components). 

If you do not have prior knowledge you should also consider using Holoplex.

**Comment by Cyncra** [comment]
> Thank you, man! lmao
> 
> 1 - I will update the repo to feature the counter soon
> 
> 2 - You can easily customize by using tailwind.css (dyor a bit the website but it is really easy to use, just grab the CSS classes and input into the className of components).
> 
> If you do not have prior knowledge of development you should also consider using https://www.holaplex.com/.

thank you for your kindness.
i tryed to modify tailwind.css. but very hard to me!
holaplex can use candymachine?

**Comment by kevinfaveri** [comment]
Sorry friend, but you need to know how to develop with React and Tailwind to work with this repo. I think Holaplex does not support Candy Machine, unfortunately.
