### ISSUE TITLE
Cannot read property '_bn' of undefined

### ISSUE THREAD

**Issue by henry8th** [kevinfaveri/solana-candy-factory#22]
Hello!

This error is occuring with the latest version of metaplex cli.
Any help would be greatly appreciated

Thanks

**Comment by kevinfaveri** [comment]
Please details the step to reach this error. Also, screenshot to me your nfts-sources folder (I mean, not the files themselves, but the list of files).

**Comment by henry8th** [comment]
Thanks for getting back to me..
I precisely followed all installation instructions of metaplex, solana cli and your package i ran all commands leading up to yarn start-dev and they worked great.

The issue is with the command start-dev, I looked at your scripts and the problem is with the command

ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env devnet --keypair ~/.config/solana/candyfactory-devnet.json --price 1

So it seems to be an issue with the metaplex client.. if you have any insights into how to fix this that would be awesome as there response rate is low..

Thank you again :)

**Comment by henry8th** [comment]
I found the error by going back and debugging the metaplex code i bascially just had to do everything manually and it worked.. thanks

**Comment by kevinfaveri** [comment]
Hello @henry8th! What exactly you had to do manually?

**Comment by henry8th** [comment]
So I ran the metaplex commands to upload and create candy machine and
realised my files where the wrong size

**Comment by kevinfaveri** [comment]
Wrong size? what do you mean by that?

**Comment by henry8th** [comment]
As in megabytes

**Comment by Adasboy** [comment]
Hi, torphix.
What do you mean "As in megabytes"
