### ISSUE TITLE
yarn setup-dev stalling at "[INFO] Setting minting start date (goLiveDate)"

### ISSUE THREAD

**Issue by maxwellfortney** [kevinfaveri/solana-candy-factory#27]
I'm attempting to run `yarn setup-dev` however the script appears to stall at the `[INFO] Setting minting start date (goLiveDate)` phase no matter what timestamp I supply. I've tried multiple different time stamps  in the future and past, with no success. 

It does not progress past this line after waiting many minutes. 
![image](https://user-images.githubusercontent.com/29241388/135764634-0a9a6fd2-4ffe-44f9-bdf2-ab75a93b685a.png)

**Comment by Tarnn** [comment]
I'm getting the same issue, can we close the process?

**Comment by maxwellfortney** [comment]
@Tarnn You can use my repo here. I've had much more success and good feedback using it. I basically simplified this repo by removing all the nft-manager stuff and wrote a more concise guide. 

https://github.com/maxwellfortney/next-candy-machine

**Comment by kevinfaveri** [comment]
Btw, the repo and scripts have been updated too @maxwellfortney, so please try again. If the issue persists, feel free to reopen here.
