### ISSUE TITLE
Batch upload n number of NFTs

### ISSUE THREAD

**Issue by alexander-io** [kevinfaveri/solana-candy-factory#28]
Say I already have my images and jsons formatted. Consider implementing a function which allows upload of these assets in batch

**Comment by maxwellfortney** [comment]
I believe you can just place them in `/nft-sources/`

**Comment by kevinfaveri** [comment]
Hey @alexander-io! @maxwellfortney is right, just place them in the `nft-sources` folder and it should work as expected. (Remember tho that it must start with 0.json / 0.png).

@maxwellfortney Thank you for supporting folks in the issues!
