### ISSUE TITLE
how to show up startmintdate count down?

### ISSUE THREAD

**Issue by Cyncra** [kevinfaveri/solana-candy-factory#3]
clone repo git not work count down :)

**Comment by kevinfaveri** [comment]
Please provide more info on why it did not work. 

Things I can think of: The countdown will only after you generate the mint machine.

**Comment by Cyncra** [comment]
> Please provide more info on why it did not work.
> 
> Things I can think of: The countdown will only work after you generate the mint machine (it is specified in the readme.md)

i just set metaplex update_candy_machine --env devnet --keypair C:\Users\Synesso\.config\solana\devnet.json -d "20 Sep 2021 22:00:00 GMT"

just not work plain solana candy factory mint page

not show up count down..

**Comment by kevinfaveri** [comment]
Oh, okay. You should read the readme.md okay? There we have some scripts, you then go on, install nodejs, and run them. Unfornelety, you do need programming knowledge to work with this repo, okay? Since this one is not a solution like Holaplex.

Just noticed: I need to update the `devtools` scripst to use `update_candy_machine` and not `set_start_time` since they updated the CLI.

**Comment by Cyncra** [comment]
> Oh, okay. You should read the readme.md okay? I do not mean to be rude.
> 
> There we have some scripts, you then go on, install nodejs, and run them. Unfortunately, you do need programming knowledge to work with this repo, okay? Since this one is not a solution like Holaplex.
> 
> Just noticed: I need to update the `devtools` scripts to use `update_candy_machine` and not `set_start_time` since they updated the CLI.


![KakaoTalk_20210920_123652306](https://user-images.githubusercontent.com/90477148/133954847-81666880-33c1-49e0-a5a2-ff2d5d6c62ed.png)

haha in metaplex community many peoples want candymachine react app ui template ~!!

i don't have web knowledge. but I'm learning. Thanks to you

**Comment by kevinfaveri** [comment]
I think Holaplex will probably work on a solution soon. But that's cool that you are learning! Wish you good luck :)
