### ISSUE TITLE
A has_one constraint was violated

### ISSUE THREAD

**Issue by traderkeo** [kevinfaveri/solana-candy-factory#30]
When conducting Mint ":A has_one constraint was violated" error is presented.
![image](https://user-images.githubusercontent.com/57576054/136145964-6efb55dc-2d59-4ec4-81a5-37289702ff78.png)

**Comment by traderkeo** [comment]
![image](https://user-images.githubusercontent.com/57576054/136146279-8001c121-7d56-420a-9d40-1c8fcc90d416.png)

**Comment by andiradulescu** [comment]
See my comment here https://github.com/kevinfaveri/solana-candy-factory/issues/35#issuecomment-939545415. Hope it helps!

**Comment by kevinfaveri** [comment]
Hey @traderkeo please validate your JSON files have a "symbol" key and the "name" key value is not that long (try with something `#1` for example). Also, the NFT Manager is not supported any more in this project, and some other tools have been suggested. Please, try again with the new repo and if it is the case, reopen the issue: https://github.com/kevinfaveri/solana-candy-factory#others-tools

PS: @andiradulescu Thank you for your support on the issues man, really appreciate it!
