### ISSUE TITLE
generate-nfts-sources not working?

### ISSUE THREAD

**Issue by Sptz** [kevinfaveri/solana-candy-factory#31]
Hi everyone,

I've followed the guide from quicknode as well as the documentation from this very repo and after creating a collection and its NFTs, the command `yarn update-creator-all-rows` works as intended but then `yarn generate-nfts-sources`, after asking if I want to randomize or not is done in around 1-2 seconds and no outputs can be seen anywhere. They should be landing in the cloned repo folder under nfts-sources correct?

Thanks

**Comment by sdkayy** [comment]
Make sure you have published the collection and the nfts associated, had the same issue before I realized.

**Comment by kevinfaveri** [comment]
Hey @Sptz @sdkayy NFT Manager support has been dropped. From now on, use third party tools to create your sources. Creating the candy machine and the web app that connects to it, still remains supported by this repo and is it sole goal from now on. I have suggested some tools for generating sources here https://github.com/kevinfaveri/solana-candy-factory#others-tools
