### ISSUE TITLE
Edit candymachine rust program and deploy

### ISSUE THREAD

**Issue by asa93** [kevinfaveri/solana-candy-factory#32]
I'm trying to implement a whitelist feature in my candy machine

I found what I should change and where, but I struggle to build and deploy the program

How should I proceed for deployment ? Does anyone have a script for that ?

**Comment by kevinfaveri** [comment]
I'm afraid the metaplex GitHub is better suited for this. But personally, I also did not manage to do that. But if you manage to, please share with here bro

**Comment by asa93** [comment]
sure
