### ISSUE TITLE
Error in generate sources after asking if I want to shuffle 

### ISSUE THREAD

**Issue by gw19191** [kevinfaveri/solana-candy-factory#33]
I am getting this error after being asked if I want to shuffle no matter what i put as a response.

![image](https://user-images.githubusercontent.com/71183797/136496404-dfd3d46c-010b-4bf7-8aea-fa21851791de.png)
(node:3500) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile './publicundefined' -> '../nfts-sources/0.png'
    at Object.copyFileSync (fs.js:2059:3)
    at generateNftsSources (C:\Users\gagew\Documents\candy-factory\solana-candy-factory-main\nft-manager\scripts\generate-nfts-sources.js:65:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 4.51s.

**Comment by gw19191** [comment]
the 0.png files arent being produced either. anyone have any suggestions?

**Comment by kevinfaveri** [comment]
Hey @gw19191! NFT Manager with Strapi support has been dropped. I suggested some other tools here: https://github.com/kevinfaveri/solana-candy-factory#others-tools

Please try with them, and if you still have an issue, open here again.
