### ISSUE TITLE
How To Create A Seperate Database For Different Projects

### ISSUE THREAD

**Issue by jackrobsonalpha** [kevinfaveri/solana-candy-factory#39]
Hi, I'm planning to use this repo. for a couple different projects in parallel.

I've cloned the repo. to two different folders on my local machine.

However, when I get to running `yarn start-nft-manager-db` an `yarn nft-manager` in my second folder, I'm pretty sure it's the same database again.

I say this because I don't get prompted to create a Strapi account (like I did the first time).

How it looks now:
<img width="814" alt="Screenshot 2021-10-14 at 16 32 18" src="https://user-images.githubusercontent.com/88769091/137350106-ed1fa414-1684-430a-bbf4-616a526ef07f.png">

I have forgotten my Strapi account login (and can't recover it through the local machine).

Is there a way to have a seperate database for each folder / instance of the repo.?

**Comment by kevinfaveri** [comment]
The NFT-Manager has been removed from this project. It adds unnecessary complexity. You should use some tool for creating your art. I recommend you check `Others Tools` on the readme.md.
