### ISSUE TITLE
If the time is not reach starttime countdown should appear, but there is only MINT.

### ISSUE THREAD

**Issue by Cyncra** [kevinfaveri/solana-candy-factory#5]
thanks to ur update!
but still countdown render in mint button not work
the time is not reach countdown should appear, but there is only MINT <<

  const [isActive, setIsActive] = useState(false); // true when countdown completes

this countdown seems to will isActive value false > true change function but not work..

				onMount={({ completed }) => completed&& setIsActive(true)}

this code always change isActive const true..

Countdown is always being set to completed on first tick.

If remove onMount and onComplete it shows the proper countdown, but then it never updates to being active.

**Comment by kevinfaveri** [comment]
No, your assumption is wrong. It only sets to active if it is completed. You might need to investigate why it is not working as expected to you... I would probably need your code (use a git fork or something here on Github so people can give you assistance) to help further since for me, running just `yarn setup-dev` and then `yarn dev` work as expected. Note tho: You do need to add at least 1 NFT using the nft manager, and then run `yarn generate-nft-sources` for this to work.

**Comment by Cyncra** [comment]
> No, your assumption is wrong. It only sets to active if it is completed. You might need to investigate why it is not working as expected to you...
> 
> I would probably need your code (use a git fork or something here on Github so people can give you assistance) to help further since for me, running just `yarn setup-dev` and then `yarn dev` work as expected.
> 
> **Note tho**: You do need to add at least 1 NFT using the nft manager, and then run `yarn generate-nft-sources` for this to work otherwise the `yarn setup-dev` command will not work as expected. **(I suspect this is what is happening... You are not doing these steps... They are exemplified in README.MD)**
> 
> Also, feel free to follow this thoughtful guide from @nheingit that is probably better than my own README.MD: https://www.quicknode.com/guides/web3-sdks/how-to-mint-an-nft-on-solana-using-candy-machine

i just use ur vanilla source code. yarn install and build and dev but not work.
countdown is work. 
but this code
 onMount={({ completed }) => completed && setIsActive(true)}
being on first tick up isActive(true)

is something wrong in my js node?
