### ISSUE TITLE
Upload was not successful, rerunning

### ISSUE THREAD

**Issue by advanztek** [kevinfaveri/solana-candy-factory#52]
Hi @kevinfaveri, thanks for your great effort on this project.

I run into this error after uploading and about 6 SOL has already been deducted. However I deployed it on the devnet and everything worked fine. 

Writing indices 1720-1729
Writing indices 730-739
Writing indices 1730-1739
Writing indices 740-749
Writing indices 1740-1749
Writing indices 750-759
Writing indices 1750-1759
Writing indices 760-769
Writing indices 1760-1769
Writing indices 770-779
Writing indices 1770-1779
Writing indices 780-789
Writing indices 1780-1789
Writing indices 790-799
Writing indices 1790-1799
Writing indices 800-809
Writing indices 1800-1809
Writing indices 810-819
Writing indices 1810-1819
Writing indices 820-829
Writing indices 1820-1829
Writing indices 830-839
Writing indices 1830-1839
Writing indices 840-849
Writing indices 1840-1849
Writing indices 850-859
Writing indices 1850-1859
Writing indices 860-869
Writing indices 1860-1869
Writing indices 870-879
Writing indices 1870-1879
Writing indices 880-889
Writing indices 1880-1889
Writing indices 890-899
Writing indices 1890-1899
Writing indices 900-909
Writing indices 1900-1909
Writing indices 910-919
Writing indices 1910-1919
Writing indices 920-929
Writing indices 1920-1929
Writing indices 930-939
Writing indices 1930-1939
Writing indices 940-949
Writing indices 1940-1949
Writing indices 950-959
Writing indices 1950-1959
Writing indices 960-969
Writing indices 1960-1969
Writing indices 970-979
Writing indices 1970-1979
Writing indices 980-989
Writing indices 1980-1989
Writing indices 990-999
Writing indices 1990-1999
Done. Successful = false.

Please what should I do right now. Am really frustrated.
THank you.

**Comment by advanztek** [comment]
Hi @kevinfaveri I reuploaded everything for the second time.

Then running this command 
ts-node ~/metaplex/js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env mainnet-beta --keypair ~/.config/solana/candyfactory-mainnet.json --price 0.49 > ./logs/main/candy-machine-log.txt

I got the error below. Please any form of help will be appreciated.

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 21820 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
(node:17216) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (C:\Users\user\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (C:\Users\user\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dant89** [comment]
@advanztek how did you fix this?

**Comment by advanztek** [comment]
> @advanztek how did you fix this?

Hi @dant89, it seems like your NFTs names or description are too long. So go to cache and change to false the ones that have a long name or have an issue. After that run the metaplex upload command again.
