### ISSUE TITLE
update_info

### ISSUE THREAD

**Issue by MikeHeid** [kevinfaveri/solana-candy-factory#55]
when updating address, update_info resolves address field into the root of the json file, not under the properties

**Comment by kevinfaveri** [comment]
Sorry... What do you mean by that? I don't get your question

**Comment by MikeHeid** [comment]
If you update the creator address and run update_info, it does not put the creator address in it's hierarchy ie. under "properties".  For me, it put it into the root. ie. not under "properties."   If i get the opportunity, i will create a video.

**Comment by kevinfaveri** [comment]
Hmm... Sure, please send more details. I'm not sure where in this repo there is a "update_info" feature... Are you sure this is not a question for the Metaplex repository?
