### ISSUE TITLE
Uploaded Successful but unable to create_candy_machine

### ISSUE THREAD

**Issue by advanztek** [kevinfaveri/solana-candy-factory#56]
uploaded all 2500 assets it was a success! And then running create_candy_machine causes an error below.

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 21820 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
(node:11000) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (C:\Users\user\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (C:\Users\user\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kevinfaveri** [comment]
@advanztek Please open this issue on Metaplex repo. But my bet is you either did upload more or less than you should have had uploaded to your cache config file. Might be wrong about this tho.

**Comment by kevinfaveri** [comment]
It probably also has a bigger error message than this one that shows more about it.

**Comment by kevinfaveri** [comment]
Also try running upload command again and then creating the candy machine after

**Comment by advanztek** [comment]
Hi @kevinfaveri, I updated some of the json files that were having issues and changed the chain in the cache to false and run the upload command again and everything worked fine.

Thank you for your assistance.

**Comment by advanztek** [comment]
Yarn build keeps on giving this error


yarn run v1.22.5
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
error - ESLint must be installed in order to run during builds: yarn add --dev eslint
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at Object.3924 (C:\Users\user\ssscc\solana-candy-factory\.next\server\chunks\924.js:29:20)
    at __webpack_require__ (C:\Users\user\ssscc\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at Object.9064 (C:\Users\user\ssscc\solana-candy-factory\.next\server\pages\_app.js:21:83)
    at __webpack_require__ (C:\Users\user\ssscc\solana-candy-factory\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (C:\Users\user\ssscc\solana-candy-factory\.next\server\pages\_app.js:155:39)
    at C:\Users\user\ssscc\solana-candy-factory\.next\server\pages\_app.js:156:70
  type: 'NodeError',
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
