### ISSUE TITLE
Error mint greater 2 nfts

### ISSUE THREAD

**Issue by linhnguyengts** [kevinfaveri/solana-candy-factory#59]
![image](https://user-images.githubusercontent.com/48374100/140698531-71e379c9-f340-4405-b9d3-86c55064190d.png)
When i mint from 3 nfts phantom wallet cannot estimate fee.

**Comment by kevinfaveri** [comment]
I was not able to make this work. My bet is that phantom is not estimating the total fees of bigger instructions. I suggest you send a support ticket to them.

**Comment by linhnguyengts** [comment]
@kevinfaveri Thank you i will send ticket to phantom
