### ISSUE TITLE
Issue while uploading ~700 files

### ISSUE THREAD

**Issue by rohanm19** [kevinfaveri/solana-candy-factory#60]
Hi,

I am getting the following error while uploading :

Writing indices 670-678
saving config line 660-669 failed ProgramError:
    at Function.parse (E:\Blockchains\Solana\Libraries\metaplex\js\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as addConfigLines] (E:\Blockchains\Solana\Libraries\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 303,
  msg: 'Index greater than length!'

Can anyone help?

**Comment by rohanm19** [comment]
My cache file shows a list of arweave urls, i also did a test run for 1 file upload and then the remaining 700, i did not manually clear my cache folder. Is that a possible issue?

**Comment by rohanm19** [comment]
when i run deployment again it shows this error:
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 2651 out of range for slice of length 496', nft-candy-machine/src/lib.rs:320:18

**Comment by kevinfaveri** [comment]
> My cache file shows a list of arweave urls, i also did a test run for 1 file upload and then the remaining 700, i did not manually clear my cache folder. Is that a possible issue?

It is. You also can incrementally upload, it will throw an error. You need to either get your config id and follow the disaster handling guide or restart the process all over again from the beginning. 

This is not an error from this repo, so I'm closing.

**Comment by rohanm19** [comment]
Thanks, sorry just to make sure i dont repeat this in the future, does it mean the SOL used for the first upload is gone? Disaster handling - > will this actually work in this case? My mainnet cache file was already present

**Comment by kevinfaveri** [comment]
If you want to get the older candy machine config ids that has your sol you can use this tool: https://aiphotos.art/find-candy-machine-configs

Then replace the config id as per the disaster handling guide from this repo using these candy machine configs.
