### ISSUE TITLE
Estimated balance changes not showing

### ISSUE THREAD

**Issue by rohanm19** [kevinfaveri/solana-candy-factory#61]
Hi,

The estimated balance changes doesn't show for me. Any pointers on how i can fix this?

![image](https://user-images.githubusercontent.com/54014510/141690356-b9c0e203-01e1-433e-8e49-08f02b121d01.png)

**Comment by kevinfaveri** [comment]
It is this error https://github.com/kevinfaveri/solana-candy-factory/issues/59 or you have a problem with your candy machine that you need to fix.
