### ISSUE TITLE
Some question!!!

### ISSUE THREAD

**Issue by AnhNPT** [kevinfaveri/solana-candy-factory#62]
Hello there, i have some question about your customize candy machine (candy-factory)
I've read the readme.md but i dont understand it clearly.

1. How much nfts art I can mint in 1 times? (mainnet and devnet)
2. Is the multiple mint function work on the mainnet environment?
3. Can I using your candy-factory in the testnet?
4. I see the folder "nft-sources", what does it mean on the candy-factory? Is that important?
I dont copy my nfts arts and json file into it but i dont see any errors, I can run the candy factory, mint all nft and it's show up in my phantom account normally. 
5. What's "NEXT_MINT_PRICE_SOL=0" meaning?

Thanks for the reading, hope you reply soon :D

**Comment by kevinfaveri** [comment]
1 - You can, just use the mintMultiple function.
2 - It works.
3 - Yes.
4 - It is. You should copy your PNG/JSON metadata files in there.
5- You should change this to be your mint price.
