### ISSUE TITLE
cannot receive solana network api

### ISSUE THREAD

**Issue by Cyncra** [kevinfaveri/solana-candy-factory#8]
i use vercel host.
first deploy on vercel. is nice work!
https://mylittledino-0xtales.vercel.app/

but setting my custom domain 

https://mylittledino.art/

cannot call solana network api haha example item remaning counts.

occured cors error

**Comment by kevinfaveri** [comment]
Yeah! The mainnet API from the Solana Labs might not be suitable. You probably need an API node which supports more calls. The serum one tho might work in the meantime until you register into something like quicknode.

**Comment by Cyncra** [comment]
> Yeah! The mainnet API from the Solana Labs might not be suitable. You probably need an API node which supports more calls. The serum one tho might work in the meantime until you register into something like quicknode.

haha another issue~!
solana network api not allowed .art domain haha :)
i changed another domain. after works fine!
