### ISSUE TITLE
yarn setup-dev displaying errors

### ISSUE THREAD

**Issue by advanztek** [kevinfaveri/solana-candy-factory#9]
Hi Kevin, thank you for taking your time to share knowledge and hence prepare the solana nft candy factory. I have everything working fine but when i run 'yarn set-dev' i run into the error below.

PS C:\Users\user\Desktop\nft_sol\solana-candy-factory> yarn setup-dev
yarn run v1.22.5
$ yarn setup-solana-dev && yarn setup-metaplex-dev && yarn setup-envs-dev
$ ./devtools/dev/setup-solana-dev.sh
$ node ./devtools/dev/setup-metaplex-dev.js
Type mint price [default 1 sol]:
Type start date of the minting [default 16 Sep 2021 00:00:00]:
'sh' is not recognized as an internal or external command,
operable program or batch file.
$ node ./devtools/dev/setup-envs-dev.js
C:\Users\user\Desktop\nft_sol\solana-candy-factory\devtools\dev\setup-envs-dev.js:33
      NEXT_PUBLIC_TREASURY_ADDRESS = fileContent.toString().split('\n')[4].split(' ')[1].trim();
                                                                          ^

TypeError: Cannot read property 'split' of undefined
    at C:\Users\user\Desktop\nft_sol\solana-candy-factory\devtools\dev\setup-envs-dev.js:33:75
    at Array.forEach (<anonymous>)
    at C:\Users\user\Desktop\nft_sol\solana-candy-factory\devtools\dev\setup-envs-dev.js:13:9
    at FSReqCallback.oncomplete (fs.js:180:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fletchertyler914** [comment]
I believe this issue stems from an earlier issue. When running setup-dev, it creates a new wallet and request an airdrop of 10 SOL. There is now a limit of 1 SOL, so the config upload fails because there is no SOL to send the transaction. I have issued a PR to drop it down to 1 and it seems to work.

**Comment by advanztek** [comment]
> I believe this issue stems from an earlier issue. When running setup-dev, it creates a new wallet and request an airdrop of 10 SOL. There is now a limit of 1 SOL, so the config upload fails because there is no SOL to send the transaction. I have issued a PR to drop it down to 1 and it seems to work.
> 
> @kevinfaveri could confirm and approve the PR if i'm right.

@fletchertyler914 Thank you  so much for your contribution and how can I change it to 1 SOL

**Comment by advanztek** [comment]
> > I believe this issue stems from an earlier issue. When running setup-dev, it creates a new wallet and request an airdrop of 10 SOL. There is now a limit of 1 SOL, so the config upload fails because there is no SOL to send the transaction. I have issued a PR to drop it down to 1 and it seems to work.
> > @kevinfaveri could confirm and approve the PR if i'm right.
> 
> @fletchertyler914 Thank you so much for your contribution and how can I change it to 1 SOL

After setting it to 1 SOL I still get the error, I think the issue is with metaplex.

**Comment by kevinfaveri** [comment]
@advanztek I think your metaplex cli is outdated. You need to use the latest version, so I suggest you build the latest one as per the guide featured in the readme.md. They changed outputs and stuff in the latest update so it breaks the devtools scripts.

**Comment by advanztek** [comment]
> @advanztek I think your metaplex cli is outdated. You need to use the latest version, so I suggest you build the latest one as per the guide featured in the readme.md. They changed outputs and stuff in the latest update so it breaks the devtools scripts.

Thank you for your reply, I've updated it however this is the error that i get now



$ yarn setup-dev
yarn run v1.22.5
$ yarn setup-solana-dev && yarn setup-metaplex-dev && yarn setup-envs-dev
$ ./devtools/dev/setup-solana-dev.sh

$ node ./devtools/dev/setup-metaplex-dev.js
Type mint price [default 1 sol]: 1
Type start date of the minting [default 26 Sep 2021 00:00:00]:
[INFO] Cleaning older cache folder for metaplex
[INFO] Uploading all resources
[INFO] Creating candy machine
[INFO] Setting minting start date (goLiveDate)
$ node ./devtools/dev/setup-envs-dev.js
C:\Users\user\Desktop\nft_sol\solana-candy-factory\devtools\dev\setup-envs-dev.js:33
      NEXT_PUBLIC_TREASURY_ADDRESS = fileContent.toString().split('\n')[4].split(' ')[
1].trim();

  ^

TypeError: Cannot read property 'trim' of undefined
    at C:\Users\user\Desktop\nft_sol\solana-candy-factory\devtools\dev\setup-envs-dev.
js:33:89
    at Array.forEach (<anonymous>)
    at C:\Users\user\Desktop\nft_sol\solana-candy-factory\devtools\dev\setup-envs-dev.
js:13:9
    at FSReqCallback.oncomplete (fs.js:180:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kevinfaveri** [comment]
Could you provide a codesandbox with the repo you are working on? Or a stackblitz? Or a Github fork so I can reproduce locally? Feel free to hide your art content, obviously.

**Comment by advanztek** [comment]
> Could you provide a codesandbox with the repo you are working on? Or a stackblitz? Or a Github fork so I can reproduce locally? Feel free to hide your art content, obviously.

@kevinfaveri I really appreciate for your help, I will do that now. Am already frustrated.

**Comment by advanztek** [comment]
> Could you provide a codesandbox with the repo you are working on? Or a stackblitz? Or a Github fork so I can reproduce locally? Feel free to hide your art content, obviously.

@kevinfaveri am having issues upload the project to github since it's over 100mb in size, the zip is 235mb though, is there any other way that I can send it to you?

**Comment by kevinfaveri** [comment]
I think you can just remove the source files maybe for your art to give room to the project

**Comment by advanztek** [comment]
> I think you can just remove the source files maybe for your art to give room to the project

@kevinfaveri I found the error and fixed it.

 if (fileDir.includes('new-wallet-log.txt')) {
      const fileContent = fs.readFileSync(fileDir);
      NEXT_PUBLIC_TREASURY_ADDRESS = fileContent.toString().split('\n')[4].split(' ')[1].trim();
    }
This block of code wasn't able to run because it wasn't able to trim the 'new-wallet-log.txt' and get the public address.
So i copied the address and pasted it as the value of NEXT_PUBLIC_TREASURY_ADDRESS, then everything work fine.

I really want to say thank you for responding to my complaints it really means alot to me.

I would like to know if it's possible for me to connect my frontend to the project as my frontend is html and css and if possible how can i achieve that, else how can i go about it as i would like to know how to develop a minting website. There's very little knowledge out there.

Looking forward to your response soon.
Thank you.

**Comment by advanztek** [comment]
Please @kevinfaveri how can I upload the project on a server, please any form of material or material will be appreciated.
I have a vps hosting on namecheap and would love to push the project there. 

Thank you for your response.

**Comment by advanztek** [comment]
> I believe this issue stems from an earlier issue. When running setup-dev, it creates a new wallet and request an airdrop of 10 SOL. There is now a limit of 1 SOL, so the config upload fails because there is no SOL to send the transaction. I have issued a PR to drop it down to 1 and it seems to work.
> 
> @kevinfaveri could confirm and approve the PR if i'm right.

Please how can I upload the project on a server, please any form of material or material will be appreciated.
I have a vps hosting on namecheap and would love to push the project there.

Thank you for your response.

**Comment by kevinfaveri** [comment]
Hey @advanztek please read this and pull the changes please: https://github.com/kevinfaveri/solana-candy-factory/issues/13#issuecomment-927367084 

Should be working now

**Comment by advanztek** [comment]
> Hey @advanztek please read this and pull the changes please: [#13 (comment)](https://github.com/kevinfaveri/solana-candy-factory/issues/13#issuecomment-927367084)
> 
> Should be working now

Thank you, I've fixed that. My major issue now is how to deploy it to a hosting server.

**Comment by advanztek** [comment]
Hi @kevinfaveri I know I've disturbed you alot, but I'll really be grateful if you can show me the steps of uploading candy machine to a hosting platform or maybe a reference for doing that. Am really stuck and don't know how to upload the website since it doesn't have an index.html.

**Comment by kevinfaveri** [comment]
You can use Vercel which is really easy to use. Or add `&& next export -o build/` to generate a plain static html.

**Comment by advanztek** [comment]
> You can use Vercel which is really easy to use. Or add `&& next export -o build/` to generate a plain static html.

Thank you so much @kevinfaveri you'll get a good news from me soon, you're the best man.

**Comment by kevinfaveri** [comment]
Thank you too bro, all the best!

**Comment by advanztek** [comment]
Hi @kevinfaveri how can I retrieve my artworks and display them in my index.tsx, which of the object holds the data or which component should  I import?
 Thank you in advance.

**Comment by advanztek** [comment]
> Thank you too bro, all the best!

Hi @kevinfaveri, I know I have disturbed you a lot but please shine a little on this for me please.

"Hi @kevinfaveri how can I retrieve my artworks and display them in my index.tsx, which of the object holds the data or which component should I import?

Basically what am trying to achieve is pull the data and display it on the website so people can mint, and so it also show the status of each artwork whether it has been minted or not, So if there's a way that I can fetch the data I will like to know.

Really looking forward to your response ASAP if possible bro, your help will really be appreciated.
Thank you in advance."
